### PR TITLE
Port to Python 3 and PyGi

### PR DESCRIPTION
**Pull request by quintusfelix**
Hi,
please consider merging my changes. I ported PyRoom to python 3 and pygi, added some missed bug fixes to the changelog and merged the bzr-branch from Jeffrey Flake (from 2014 i think). This was done due to the fact that python 2 isn't supported after the 1. Januar 2020 any more, and that there is no pyroom debian package in buster (debian 10). Although that's a big change, i tryed to be as little invasive as possible.
My future plans would be:
* reenable debian packaging
* merge plugins (from bzr) and stabilize plugin system
* replace any deprecated (<3.20) Gtk/Gdk/Pango functionality
    * Gdk.Color -> Gdk.RGBA
    * widget.modify_* -> widget.override_* 
    * ...
* rebuild main gui with glade
* convert main gui styling (and themes) to css
* create solarized dark/light themes
* darken even second and third monitor (configurable)

### CODE REVIEW

**Comment by very-emmazing** [comment]
Hi, thanks for the awesome pull request!

As you can probably tell I'm not really involved in coding PyRoom any more. 

Would you like to take over the project? I'm not sure what would be involved. Originally, development happened on Launchpad but I suppose GitHub would be the choice for that today.

**Comment by quintusfelix** [comment]
Hi, thanks, that was a lot of work. But I had a loads of fun doing it. Of course I had hoped to revive the project, not to take it over. However, since pyroom is my favorite text editor for creative writing and i'm interested in PyGi and i want to get into Debian package creation, I'm willing to accept this offer.

Yes, github should be the hosting platform i think. But what about pyroom.org? I don't have the time to maintain a website (yet). Maybe there could be a redirect to a github wiki page? Do you want to grant me access to fheinle/PyRoom or should the development happen at quintusfelix/PyRoom?

**Comment by very-emmazing** [comment]
I think the best idea would be for you just to maintain the code in your personal namespace where you have full access. My mirror here is nothing special; the original source code was on launchpad anyway. So your's is as good as mine I suppose :-)

Concerning the homepage I think you should ask Bruno Bord, who lead development some time ago and who's hosting the homepage. I believe the source code is still just a bunch of markdown files with a custom script that compiles those to html using some templates, nothing special. It should be pretty easy to maintain if you want to use the homepage. It's from 2009 though, so don't expect anything fancy :-) 

I guess the easiest way to reach Bruno would be on his twitter on https://twitter.com/brunobord

**Comment by quintusfelix** [comment]
Oops, i didn't expected this topic to be closed on branch deletion - although this seams reasonable now ;-)

Thanks for the information, i will try to contact him :-)

Meanwhile i have detached the PyRoom fork from your repository. Now i'm working on reenabling the debian packaging and i have a few more questions before i proceed. Maybe you could spare some time in answering.
* if i'm done with the debian package: whom should i contact to put it back into debian repositories?
* what where your future plans back in 2010 with pyroom (besides the plugin system)? 
* do you have the PyRoom icon as vector image?

**Comment by very-emmazing** [comment]
>  whom should i contact to put it back into debian repositories?

PyRoom is still in debian stable but appears to have been dropped in testing and unstable. You could contact [Kartik Mistry](https://qa.debian.org/developer.php?login=kartik%40debian.org) wo packaged it for Debian. When the package is in Debian, it should also appear in Ubuntu again

> future plans

Not too many for the core program but some features as plugins: version control integration, i.e. making a new commit when saving a file or allowing the user to post the currently open file to a blog of some sorts. This was back when LiveJournal was still big for people wo write prose, maybe today that would be tumlr? No idea honestly.

> do you have the PyRoom icon as vector image?

I'm afraid I don't.

**Pull request closed without merging**
